server {
    listen 8080;
    client_body_size 6546;
    root ./www;
    index index.html;

    location /image {
        root .;
        allow_methods GET DELETE POST        ;
        index maha.html;
        client_body_size 222;
    }
}