server {
    listen 9091;
    server_name localhost;

    root /mnt/homes/massrayb/Desktop/web-server/page;
    index index.html;

    location / {
        autoindex off;
    }

    error_page 404 /404.html;
}